// Generated by CoffeeScript 1.10.0
(function() {
  var CWD, MySqlAdapter, Waterline, _, def, diskAdapter, loadedModels, memoryAdapter, orm, waterlineLoader;

  _ = require('lodash');

  Waterline = require('waterline');

  def = require('def-type');

  memoryAdapter = require('sails-memory');

  diskAdapter = require('sails-disk');

  MySqlAdapter = require('sails-mysql');

  orm = new Waterline();

  loadedModels = null;

  CWD = process.cwd();

  waterlineLoader = def.Module(function() {
    var _destroyModel, _getOriginalName, _loadModelIntoCollection, _loadModels, config, defaultModel, namesHashMap;
    config = {
      adapters: {
        'default': memoryAdapter,
        'memory': memoryAdapter,
        'sails-disk': diskAdapter,
        'sails-mysql': MySqlAdapter
      },
      connections: {
        memory: {
          adapter: 'memory'
        },
        localDiskDb: {
          adapter: 'sails-disk'
        }
      },
      defaults: {
        migrate: 'drop'
      },
      defaultModelConf: {
        connection: 'memory'
      }
    };
    namesHashMap = {};
    defaultModel = null;
    this.init = function(options, done) {
      var attachTo, models;
      if (options == null) {
        options = {};
      }
      models = options.models;
      delete options.models;
      config = _.merge(config, options);
      defaultModel = config.defaultModelConf;
      attachTo = options.attachTo != null ? _.isArray(options.attachTo) ? options.attachTo : [options.attachTo] : [global];
      delete config.defaultModelConf;
      _loadModels(models);
      return orm.initialize(config, function(err, orm) {
        var i, len, lowerCaseName, model, obj, ref;
        console.log('WaterlineLoader: Initializing ORM');
        if (err) {
          throw err;
        }
        loadedModels = orm.collections;
        ref = orm.collections;
        for (lowerCaseName in ref) {
          model = ref[lowerCaseName];
          model.associations = _.reduce(model.attributes, function(associatedWith, attrDef, attrName) {
            var assoc, ref1;
            if (typeof attrDef === 'object' && (attrDef.model || attrDef.collection)) {
              assoc = {
                alias: attrName,
                type: (ref1 = attrDef.model) != null ? ref1 : {
                  'model': 'collection'
                }
              };
              if (attrDef.model) {
                assoc.model = attrDef.model;
              }
              if (attrDef.collection) {
                assoc.collection = attrDef.collection;
              }
              if (attrDef.via) {
                assoc.via = attrDef.via;
              }
              associatedWith.push(assoc);
            }
            return associatedWith;
          }, []);
          if (lowerCaseName.indexOf('__') === -1) {
            global[_getOriginalName(lowerCaseName)] = model;
            for (i = 0, len = attachTo.length; i < len; i++) {
              obj = attachTo[i];
              obj[_getOriginalName(lowerCaseName)] = model;
            }
          }
        }
        return done();
      });
    };
    this.teardown = function(done) {
      console.log('WaterlineLoader: tearing down...');
      return _destroyModel(loadedModels, _.keys(loadedModels), done);
    };
    _destroyModel = function(models, modelNamesArray, done) {
      return models[modelNamesArray.pop()].destroy().then((function(_this) {
        return function() {
          if (modelNamesArray.length === 0) {
            return orm.teardown(done);
          } else {
            return _destroyModel(models, modelNamesArray, done);
          }
        };
      })(this));
    };
    _loadModels = function(models) {
      var i, len, model, modelDefinition, modelFileName;
      for (i = 0, len = models.length; i < len; i++) {
        model = models[i];
        modelFileName = _.isString(model) ? model : model.fileName;
        modelDefinition = require(CWD + "/api/models/" + modelFileName);
        if (_.isFunction(modelDefinition)) {
          if (model.afterLoadFilter != null) {
            modelDefinition = model.afterLoadFilter(modelDefinition);
          } else {
            modelDefinition = modelDefinition();
          }
        }
        _loadModelIntoCollection({
          name: modelFileName,
          definition: modelDefinition
        });
      }
      return this;
    };
    _loadModelIntoCollection = function(model) {
      var waterlineCollection, waterlineModel;
      waterlineModel = _.defaults(model.definition, {
        identity: model.name,
        tableName: model.name
      }, defaultModel);
      waterlineCollection = Waterline.Collection.extend(waterlineModel);
      orm.loadCollection(waterlineCollection);
      return namesHashMap[model.name.toLowerCase()] = model.name;
    };
    return _getOriginalName = function(lowerCaseName) {
      return namesHashMap[lowerCaseName];
    };
  });

  module.exports = waterlineLoader;

}).call(this);

//# sourceMappingURL=index.js.map
